### ISSUE TITLE
miss-spelled Khmer unicode on tcpdf

### ISSUE THREAD

**Issue by magic-overflow** [tecnickcom/tc-lib-pdf#10]
I have searched the solution and i found https://sourceforge.net/p/tcpdf/discussion/435311/thread/5d275055/ .
But i'm not sure how to do it, anyone can guide me pls?

Khmer Character list : http://www.selapa.net/khmerfonts/characterlist.php

**Comment by nicolaasuni** [comment]
This is not relevant as your issue is about the legacy TCPDF library and not this one.
