### ISSUE TITLE
signDocument() / Fix the $pdfDoc variable to have duplicates appended to the content.

### ISSUE THREAD

**Issue by mean-cj** [tecnickcom/tc-lib-pdf#104]
Hi 

**Fix signDocument() has been duplicates appended  to the pdfContent**

` return $this->sign ?  $this->signDocument($out) : $out;`

[# tc-lib-pdf/blob/main/src/Output.php](https://github.com/tecnickcom/tc-lib-pdf/blob/98de295e4f53ccccff62f20c373e5b0c5723b2aa/src/Output.php#L521)
```
    public function getOutPDFString(): string
    {
        $out = $this->getOutPDFHeader()
            . $this->getOutPDFBody();
        $startxref = strlen($out);
        $offset = $this->getPDFObjectOffsets($out);
        $out .= $this->getOutPDFXref($offset)
            . $this->getOutPDFTrailer()
            . 'startxref' . "\n"
            . $startxref . "\n"
            . '%%EOF' . "\n";
        return $out . $this->signDocument($out);
    }
```

I don't have a clue what the bug is, but it's part of the problem.
I hope to receive further development in digital signing.

**Comment by nicolaasuni** [comment]
Thank you for reporting this issue. It has been fixed.
