### ISSUE TITLE
LinearGradient prints wrong colors

### ISSUE THREAD

**Issue by gianlucagiacometti** [tecnickcom/tc-lib-pdf#11]
Hello,
this is my code:

`
$pdf->LinearGradient($x, $y, $width, $height, $darkblue, $lightblue);
`

If I give colors in RGB like
```
$darkblue = array(2, 63, 17);
$lightblue = array(170, 195, 226);
```
the result is a sort of green instead of blue

If I give colors in CMYK format
```
$darkblue = array(251, 118, 0, 138);
$lightblue = array(64, 34, 0, 29);
```
the result is different bands of different colors with very few gradient (the blu I want, but then magenta, then violet, then amaranto and then again blue)

Can you reproduce the same issue?
Some hints?

Thank you in advance

Gianluca

**Comment by nicolaasuni** [comment]
This is not relevant as your issue is about the legacy TCPDF library and not this one.
