### ISSUE TITLE
Using tc-lib-pdf without Composer, RPM or DEB

### ISSUE THREAD

**Issue by NJCLous** [tecnickcom/tc-lib-pdf#110]
Hi Nicola,

Thanks for all your work on tc-lib-pdf which, if I understand things correctly, will soon replace TCPDF. I have used TCPDF for many years now and I'd like to upgrade to tc-lib-pdf.

I was able to use TCPDF by simply downloading all files from https://github.com/tecnickcom/TCPDF/archive/refs/heads/main.zip, unzipping them to my server location (in a folder called TCPDF), and including them in my own code using

require_once('TCPDF/tcpdf.php');

Is the same approach possible for tc-lib-pdf - and if not, could you make this an option? My server doesn't allow installations via Composer and I don't know anything about RPM or DEB packages.

Thanks in advance for your help and best wishes,

Niels

**Comment by nicolaasuni** [comment]
First note that the new tc-lib-pdf library, while working, it is still missing some important TCPDF features like the ability to parse HTML/CSS/SVG. I will try to add those features but I have no ETA.

One option for your case could be building your dependencies locally (`make buildall`) and then deploy into your server.

**Comment by NJCLous** [comment]
Thanks Nicola - I'll wait until the new library is completely ready and then check with my hosting provider if "make buildall" is available on my hosting server. Good luck adding the final features and thanks for all your work on this library! - Nels

**Comment by MacGritsch** [comment]
> Thanks Nicola - I'll wait until the new library is completely ready and then check with my hosting provider if "make buildall" is available on my hosting server.

I think he means that you should do the preparation on your local system and only upload the needed files to your hosting-server.

For example you could add the following code to your pdf-generating files on your local dev-machine and echo out all needed includes. Then you can include exactly that files. You can copy all files to the hosting server or only the ones that are needed.

```
spl_autoload_register(function ($className)
{
	$map = [
		'Com\\Tecnick\\Unicode\\Data\\' => '/third-party/tecnickcom/tc-lib-unicode-data/src',
		'Com\\Tecnick\\Unicode\\' => '/third-party/tecnickcom/tc-lib-unicode/src',
		'Com\\Tecnick\\Pdf\\Parser\\' => '/third-party/tecnickcom/tc-lib-pdf-parser/src',
		'Com\\Tecnick\\Pdf\\Page\\' => '/third-party/tecnickcom/tc-lib-pdf-page/src',
		'Com\\Tecnick\\Pdf\\Image\\' => '/third-party/tecnickcom/tc-lib-pdf-image/src',
		'Com\\Tecnick\\Pdf\\Graph\\' => '/third-party/tecnickcom/tc-lib-pdf-graph/src',
		'Com\\Tecnick\\Pdf\\Font\\' => '/third-party/tecnickcom/tc-lib-pdf-font/src',
		'Com\\Tecnick\\Pdf\\Filter\\' => '/third-party/tecnickcom/tc-lib-pdf-filter/src',
		'Com\\Tecnick\\Pdf\\Encrypt\\' => '/third-party/tecnickcom/tc-lib-pdf-encrypt/src',
		'Com\\Tecnick\\Pdf\\' => '/third-party/tecnickcom/tc-lib-pdf/src',
		'Com\\Tecnick\\File\\' => '/third-party/tecnickcom/tc-lib-file/src',
		'Com\\Tecnick\\Color\\' => '/third-party/tecnickcom/tc-lib-color/src',
		'Com\\Tecnick\\Barcode\\' => '/third-party/tecnickcom/tc-lib-barcode/src',
	];
	
	foreach ($map as $tmpPrefix => $tmpSubPath)
	{
		if (str_starts_with($className, $tmpPrefix))
		{
			$tmpPath = $tmpSubPath . DIRECTORY_SEPARATOR . str_replace('\\', DIRECTORY_SEPARATOR, substr($className, strlen($tmpPrefix))) . '.php';
			
			require __DIR__ . $tmpPath;
			
			echo "INCLUDE/COPY: $tmpPath<br/>";
			
			return;
		}
	}
	
	echo "NOT FOUND $className<br/>";
});
```

For the first official example I get this output:

> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/Base.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/Cell.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/Text.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/SVG.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/CSS.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/JavaScript.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/HTML.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/MetaInfo.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/Output.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/ClassObjects.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/Tcpdf.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-encrypt/src/Type/Seed.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-encrypt/src/Output.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-encrypt/src/Data.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-encrypt/src/Compute.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-encrypt/src/Encrypt.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-color/src/Css.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-color/src/Web.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-color/src/Spot.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-color/src/Pdf.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf/src/PdfColor.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-barcode/src/Barcode.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-file/src/File.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-file/src/Cache.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-unicode/src/Convert/Encoding.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-unicode/src/Convert.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-page/src/Format.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-page/src/Mode.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-page/src/Box.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-page/src/Settings.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-page/src/Region.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-page/src/Page.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-graph/src/Base.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-graph/src/Style.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-graph/src/Transform.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-graph/src/Raw.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-graph/src/Gradient.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-graph/src/Draw.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-font/src/Buffer.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-font/src/Stack.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-image/src/Output.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-image/src/Import.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-font/src/Load.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-font/src/Font.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-file/src/Dir.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-font/src/Core.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-color/src/Model/Template.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-color/src/Model.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-color/src/Model/Cmyk.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-unicode-data/src/Type.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-color/src/Exception.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-color/src/Model/Rgb.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-font/src/OutUtil.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-font/src/OutFont.php
> INCLUDE/COPY: /third-party/tecnickcom/tc-lib-pdf-font/src/Output.php
