### ISSUE TITLE
TCpdf creating blank pdf

### ISSUE THREAD

**Issue by mukeshzt** [tecnickcom/tc-lib-pdf#12]
I'm using the TCpdf but I was facing one issue with the formatting.

In my application, we accepting the data from end users and based on provided data we create pdf using TCpdf. (using PHP)
The issue is when end users copy data from word document/ existing other pdf and paste into provided text area. so its include the word formatting and bullets and all. It's stored as it is in my database, Once I send that information to TCpdf then TCpdf skip the formatted data and generate blank pdf.

**Comment by nicolaasuni** [comment]
This is not relevant as your issue is about the legacy TCPDF library and not this one.
