### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Juventino96** [tecnickcom/tc-lib-pdf#13]
Where to see the full documentation for the new version.

**Comment by shoulders** [comment]
I am not a brilliant programmer but I understand PHP okay. I would like some simple instructions on how to install this on a simple PHP project. I use windows and do not use linux, the closes I get is ftp'ing my software to a shared server. My project software will be installed on shared servers.

thanks

**Comment by nicolaasuni** [comment]
The documentation of this new library is published at:
https://tcpdf.org/docs/srcdoc/
but this library is still incomplete and under development, so it can't yet be used as it is.
Only the dependency are in a good state but some work is still required to complete the core library.

**Comment by shoulders** [comment]
then you should remove this message 

> A new version of this library is under development at https://github.com/tecnickcom/tc-lib-pdf and as a consequence this version will not receive any additional development or support. This version should be considered obsolete, new projects should use the new version as soon it will become stable.

from https://github.com/tecnickcom/tcpdf to avoid confusion.
