### ISSUE TITLE
How to hide yellow popup when hover the link in chrome?its working fine in IE.its showing only in windows not in Ubuntu.

### ISSUE THREAD

**Issue by SsKarthi** [tecnickcom/tc-lib-pdf#15]
a href="http://sourceforge.net/donate/index.php?group_id=128076"> MAKE A DONATION!
![error](https://cloud.githubusercontent.com/assets/9975063/22287763/0c0721ea-e31a-11e6-86b1-087014a31970.png)

thanks, advance.

**Comment by nicolaasuni** [comment]
Your question refers to the legacy TCPDF project that is currently unsupported.
This is a new project that will replace TCPDF but it is not ready yet.
