### ISSUE TITLE
 Call to undefined method getOutOutput

### ISSUE THREAD

**Issue by DenisZhadan** [tecnickcom/tc-lib-pdf#17]
PHP Fatal error:  Call to undefined method Com\Tecnick\Pdf\Tcpdf::getOutOutput() in \vendor\tecnickcom\tc-lib-pdf\src\Output.php on line 109

**Comment by nicolaasuni** [comment]
This project is under development and is not yet ready.
Unfortunately you will have to wait until a minimal set of feature will be implemented.
