### ISSUE TITLE
Planned stable release date? PHP 7 support?

### ISSUE THREAD

**Issue by MacGritsch** [tecnickcom/tc-lib-pdf#18]
Hi,

Is there a release date for this new library? 2017? 2018?

Does it support PHP 7?
The old lib (but currently active one) seems not to support it?

Will it have a completly new API or could one simply migrate from the old lib to the new one?

It seems to be a great project - thank you!

**Comment by nicolaasuni** [comment]
The old library should support PHP7, I merged some changes recently.
The new library is currently progressing very slowly because I am quite busy but more than 90% of the code is there (now spread across independent libraries).

**Comment by nicolaasuni** [comment]
Note that the current version of the new library has an example that generates a blank page!
There are some ready methods also to add fonts, graphics and barcodes but some essential methods for text are still missing.

**Comment by chehmer** [comment]
Hi Nicola,

When I add Hebrew text within text annotation, I cant so it well on Chrome browser (the latest versions) but it showing good on Firefox.
chrome :
![image](https://user-images.githubusercontent.com/4460564/28233294-76a1cdce-68fe-11e7-94af-d434129ae006.png)
Firefox :
![image](https://user-images.githubusercontent.com/4460564/28233302-825f54c4-68fe-11e7-8ac0-39d965ee5cdb.png)

I think it because chrome doesn't support encoding any more...

Is the text annotation function  will support UTF-8 in the near future ? or there is others options to add the text that will be show good in Chrome ?

Thank you,
Roy

**Comment by divinity76** [comment]
i have been using the old library on php 7.0 in production for months without problems, so yeah, it supports PHP5 just fine.

**Comment by MacGritsch** [comment]
Thank you for the information.
So its best to use the old version.
Are there still plans to finish this new version?

thank you for all your efforts and best regards

**Comment by divinity76** [comment]
@mklemarczyk the current status, the way i see it (and use it) is:  the old lib is production ready, the new lib is not. so yeah, unless you're planning on helping out the development of the new version,   use the old version for now.

**Comment by semaex** [comment]
Hi, 

I have a project with old tecnickcom/tcpdf and with new php 7.2 version it doesn't work anymore.

each() method used in tcpdf.php file is deprecated.

@nicolaasuni is possible to update old version? I know is not manteined anymore but I think is a small bug and the new version is not ready yet...

Thanxs for this good library ;)

**Comment by divinity76** [comment]
@semaex a 3rd party patch is [available](https://github.com/tecnickcom/TCPDF/pull/74), but @nicolaasuni has indicated that no patches will be accepted upstream because TCPDF is "frozen"

**Comment by MacGritsch** [comment]
@semaex you can simply apply this patch:

`diff --git a/tcpdf.php b/tcpdf.php
old mode 100755
new mode 100644
index 65196e7..89223d0
--- a/tcpdf.php
+++ b/tcpdf.php
@@ -12582,7 +12582,7 @@ class TCPDF {
 		$k = $this->k;
 		$this->javascript .= sprintf("f".$name."=this.addField('%s','%s',%u,[%F,%F,%F,%F]);", $name, $type, $this->PageNo()-1, $x*$k, ($this->h-$y)*$k+1, ($x+$w)*$k, ($this->h-$y-$h)*$k+1)."\n";
 		$this->javascript .= 'f'.$name.'.textSize='.$this->FontSizePt.";\n";
-		while (list($key, $val) = each($prop)) {
+		foreach($prop as $key => $val) {
 			if (strcmp(substr($key, -5), 'Color') == 0) {
 				$val = TCPDF_COLORS::_JScolor($val);
 			} else {
@@ -16545,7 +16545,7 @@ class TCPDF {
 					// get attributes
 					preg_match_all('/([^=\s]*)[\s]*=[\s]*"([^"]*)"/', $element, $attr_array, PREG_PATTERN_ORDER);
 					$dom[$key]['attribute'] = array(); // reset attribute array
-					while (list($id, $name) = each($attr_array[1])) {
+                    foreach($attr_array[1] as $id => $name) {
 						$dom[$key]['attribute'][strtolower($name)] = $attr_array[2][$id];
 					}
 					if (!empty($css)) {
@@ -16558,7 +16558,7 @@ class TCPDF {
 						// get style attributes
 						preg_match_all('/([^;:\s]*):([^;]*)/', $dom[$key]['attribute']['style'], $style_array, PREG_PATTERN_ORDER);
 						$dom[$key]['style'] = array(); // reset style attribute array
-						while (list($id, $name) = each($style_array[1])) {
+                        foreach($style_array[1] as $id => $name) {
 							// in case of duplicate attribute the last replace the previous
 							$dom[$key]['style'][strtolower($name)] = trim($style_array[2][$id]);
 						}
`

**Comment by semaex** [comment]
Thanxs MacGritsch. I know how to solve this bug but I need the changes persist in oficial repo because my deploy system with composer downloads directly from authors repo. 

Any ideas?

**Comment by MacGritsch** [comment]
@semaex you could create a (private) fork, apply the patch and use that fork in your composer files.

**Comment by semaex** [comment]
@MacGritsch @divinity76 Thanxs for ideas, I'll do this ;)

**Comment by pyrographics** [comment]
Looking forward to the release of the new library.  What is the best way to troubleshoot PDF corruption using the old tcpdf?  Sometimes the PDF exports correctly and sometimes it is corrupted.  No error is generated so I'm stuck as to what is causing it.

**Comment by xperseguers** [comment]
Could someone tell me where to look for some basic up-to-date samples? https://tcpdf.org/examples/ are all based on an older version of the library, example in this project only shows creating a blank page, but nothing regarding adding some text, adding some graphics, adding a barcode, ...

**Comment by Ohda** [comment]
Hello. Any update on an possible release date ?

**Comment by extcode** [comment]
@semaex you can also use the official repository and use https://github.com/cweagans/composer-patches to patch the files with composer.

**Comment by semaex** [comment]
thanxs to everyone ;)

**Comment by mcgreevyd** [comment]
Any news on this?

**Comment by gnurob** [comment]
Are there ways to offer some support to this project besides coding?

**Comment by kade99** [comment]
Any news? :)

**Comment by connorhu** [comment]
@nicolaasuni Do you have any list of release blocker tasks?

**Comment by rabol** [comment]
@nicolaasuni let us know how we can help, please

**Comment by nicolaasuni** [comment]
Hi, thank you for the help offers.
People can contribute either via PR or sending donations following the link in the README.md.

The overall project is almost complete but I struggle to find the time to complete the core functions in the main library.
All the dependency libraries are complete and some of them can also be used with the old TCPDF library:

- tc-lib-barcode
- tc-lib-color
- tc-lib-pdf-image
- tc-lib-pdf-font
- tc-lib-file
- tc-lib-pdf-encrypt
- tc-lib-unicode-data
- tc-lib-unicode
- tc-lib-pdf-page
- tc-lib-pdf-graph

The main library (tc-lib-pdf) can now build a blank page.
The aim is to complete the Output.php file first and then start adding the basic functions to print a text cell, etc.

In the Output file the incomplete functions have an empty body and they are marked with a @TODO comment.

**Comment by mklemarczyk** [comment]
Super news, I will take a look in a free time to try to help with finishing the library.

**Comment by EduVillas** [comment]
What about php 8.0 ???

**Comment by gerardreches** [comment]
I need to generate PDF certificates on my site using PHP (using PHP 7.4). Does someone know if this library already works or if the old one is compatible with PHP 7.4? 

Thanks!

**Comment by xperseguers** [comment]
@gerardreches Using with PHP 7.4 for a long time, not facing any problems with my use cases.

**Comment by gerardreches** [comment]
> @gerardreches Using with PHP 7.4 for a long time, not facing any problems with my use cases.

Hi Xavier!

Are you talking about this library (the new one under development) or the old one (stable)?

Thanks!

**Comment by xperseguers** [comment]
I had a reference to that repository but after double-checking, I'm actually using `"tecnickcom/tcpdf": "dev-main",` in my `composer.json` files, so the development branch of that package.

**Comment by gerardreches** [comment]
> I had a reference to that repository but after double-checking, I'm actually using `"tecnickcom/tcpdf": "dev-main",` in my `composer.json` files, so the development branch of that package.

I will give it a try then, thank you!

**Comment by mahouha** [comment]
> I need to generate PDF certificates on my site using PHP (using PHP 7.4). Does someone know if this library already works or if the old one is compatible with PHP 7.4?
> 
> Thanks!

have you a solution ??

**Comment by xperseguers** [comment]
@mahouha Please read my answer following the question, from April last year. in short: it works! just use dev-main in your composer.json

**Comment by MacGritsch** [comment]
Old version also works with PHP 8.x
