### ISSUE TITLE
PDF preset standard.

### ISSUE THREAD

**Issue by dhaval-parekh** [tecnickcom/tc-lib-pdf#19]
Hello @nicolaasuni 
Is there is any option for pdf to convert it in to **High Quality Print** as PDF preset
![pdf-preset](https://cloud.githubusercontent.com/assets/8168027/23252906/7b6a65ae-f9d8-11e6-92ac-f12788a4748d.png)

I have created one .pdf file using TCPDF library in php. Which contain one image layer and above that one  svg path. However this part are working well, But problem is i need that .pdf file in **High Quality Print** preset standard.

Please check [attachment](http://prasad.rtcamp.info/wp-content/uploads/2017/02/format12.pdf).

Any feedback will be much appreciate.

**Comment by milindmore22** [comment]
Thanks for the opening issue, I am also looking a way to set the preset standard in TCPDF
can anyone please look into it. 
thanks in advance.

**Comment by nicolaasuni** [comment]
Since the fonts are always stored as vectors, the issue is only with images.
If you can't use vector images (SVG) than be sure to use high-quality images.
In the new library there will be an option for PDF/A and PDF/X.
