### ISSUE TITLE
Border trasparent not transparent

### ISSUE THREAD

**Issue by ossarotte** [tecnickcom/tc-lib-pdf#2]
I use the latest version of TCPDF looking forward to the new release, I have a problem with the borders of an HTML table as described in [http://stackoverflow.com/questions/38505197/tcpdf-html-table-border-not-render-correctly ](url) there is a solution or do I have to wait for the new version?

**Comment by theroch** [comment]
The old version will not receive any additional development or support.
You have to fix the problem by yourself or have to wait for the new release.

Here is a link for CSS support with tcpdf:
http://www.jennybeaumont.com/testing-tcpdf-css/

There are also some indiciations on the project website at sourceforge.net, but this site is temporarily offline.

**Comment by ossarotte** [comment]
ok tanks, waiting for new release.

**Comment by ossarotte** [comment]
no solve yet
