### ISSUE TITLE
Open an already existing PDF file

### ISSUE THREAD

**Issue by modir** [tecnickcom/tc-lib-pdf#20]
It would be great if an already existing PDF file could be opened and new pages added to it.

**Comment by nicolaasuni** [comment]
The project:
https://github.com/tecnickcom/tc-lib-pdf-parser
allows to parse an existing PDF into a structured array.
Some of this data can be added back as XObject into a new PDF document.
Potentially we can import all the document into the new pdf library but it is a long shot for now as the main library is still incomplete.

**Comment by vaultwiki** [comment]
Looking for this also:
- A simplified method of taking the output of tc-lib-pdf-parser and inserting it into tc-lib-pdf as a cloned document (so we can modify and save).

**Comment by mean-cj** [comment]
how to tc-lib-pdf-parser to tc-lib-pdf ?
I couldn't find a function to proceed with at all.
