### ISSUE TITLE
about the new lib to create a non-blank page

### ISSUE THREAD

**Issue by hainuo** [tecnickcom/tc-lib-pdf#22]
![image](https://cloud.githubusercontent.com/assets/421861/26751619/3c7feda0-4870-11e7-956b-e4484272d6dc.png)

I found that the  parameter $data of the add() method has a key called content that is used to set the contents of the pdf page. But by setting the value of the content, the pdf which is new generated is still blank. What should I do to generate normal pdf whith content?

**Comment by nicolaasuni** [comment]
This library is still incomplete and some required methods and classes are still missing.
At the current state this library can only produce a blank page.
