### ISSUE TITLE
Input Box issue

### ISSUE THREAD

**Issue by mohitwebuters** [tecnickcom/tc-lib-pdf#23]
Hi TCPDF Team

I am using TCPDF for create PDF. I want to use input box and check box in PDF. Input box is working but i am not able to add height and width for input box and check boxes. 
Please suggests me how we have to use height and width properties for input box and check boxes.

Regards
Mohit kumar
mohit.kumar@webuters.com

**Comment by nicolaasuni** [comment]
The legacy TCPDF library is not actively maintained anymore and it will be replaced by this library when completed.

**Comment by emrahu** [comment]
I have been reading the documentation and applying the code changes but nothing really changes the way checkboxes are rendered. Is there a way to control how checkboxes look?
