### ISSUE TITLE
receiving error using old library. please HELP!

### ISSUE THREAD

**Issue by Ababei-Ana-Maria** [tecnickcom/tc-lib-pdf#24]
hello, 
I have a question about the old version of the library. I'm trying to sign a pdf document and i keep getting this error : 
Warning: openssl_pkcs7_sign(): error getting private key in C:\xampp\htdocs\ANA\TCPDF-masterV3\tcpdf.php on line 7600
Notice: Undefined offset: 1 in C:\xampp\htdocs\ANA\TCPDF-masterV3\tcpdf.php on line 7610
TCPDF ERROR: Some data has already been output, can't send PDF file
Sorry for posting here but the old version doesn't have an issues section. Any help would be appreciated . Thank you very much!

**Comment by nicolaasuni** [comment]
The legacy TCPDF library is not actively maintained anymore and it will be replaced by this library when completed.
