### ISSUE TITLE
Adobe specification compliance failing with Jetty/Quercus engine

### ISSUE THREAD

**Issue by anilfunde** [tecnickcom/tc-lib-pdf#25]
I am using TCPDF with jetty and quercus engine to generate PDFs. PDF are getting generated successfully but no text at all. When i did some preflights on generated pdf i found below error 

> 
> Analyze Outlines.
> Analyze Pages.
> 0x80410503 - E - The operator has an invalid number of operands.
>     - File: server.pdf
> 0x80410513 - E - An end text operator is missing.
>     - File: server.pdf
> 0x80410113 - E - The file is corrupt and cannot be repaired. Some of the contents can possibly be recovered.
>     - Page No.: 1
>     - File: server.pdf
> Save output file.
> 0x80410503 - E - The operator has an invalid number of operands.
>     - Page No.: 1
>     - File: server.pdf
> 0x80410513 - E - An end text operator is missing.
>     - Page No.: 1
>     - File: server.pdf
> Close file.
> 3-Heights(TM) PDF repair tool, evaluation license valid until unbounded

below is code --
`        $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        $pdf->setFontSubsetting(false);

        // set document information
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Anil Funde');
        $pdf->SetTitle('TCPDF Example 002');
        $pdf->SetSubject('TCPDF Tutorial');
        $pdf->SetKeywords('TCPDF, PDF, example, test, guide');

        // remove default header/footer
        $pdf->setPrintHeader(false);
        $pdf->setPrintFooter(false);

        // set default monospaced font
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

        // set margins
        $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);

        // set auto page breaks
        $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

        // set image scale factor
        $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

        // set some language-dependent strings (optional)
        if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
            require_once(dirname(__FILE__).'/lang/eng.php');
            $pdf->setLanguageArray($l);
        }
        #$fontname = TCPDF_FONTS::addTTFfont('../fonts/TimesSRegular.ttf', 'TrueType','ansi', 32);
        
         // set font
        #$pdf->SetFont($fontname, '', 20);
        // ---------------------------------------------------------

       

        // add a page
        $pdf->AddPage();

        // set some text to print
        #$txt ="test222222222222";
        

        // print a block of text using Write()
        $pdf->Write(0, $txt, '', 0, 'C', true, 0, false, false, 0);
        
        // ---------------------------------------------------------

        //Close and output PDF document
        $pdf->Output('example_002.pdf', 'I');`

 I tried same code in XAMP enviorenment (apache/php) and it worked very well there and pdf generated in xamp environment get validated successfully.

While debugging, on jett/quercus environment i removed write() call and tried to generate blank pdf, generated pdf get validated successfully. Looks like write() and similar methods messing up something.

**Comment by nicolaasuni** [comment]
The legacy TCPDF library is not actively maintained anymore and it will be replaced by this library when completed.

**Comment by anilfunde** [comment]
just keep in mind this for current development. might be current library is having same issue.
