### ISSUE TITLE
Text annotation support utf-8

### ISSUE THREAD

**Issue by chehmer** [tecnickcom/tc-lib-pdf#26]
Hi Nicola,

When I add Hebrew text within text annotation, I cant so it well on Chrome browser (the latest versions) but it showing good on Firefox.
chrome :
![image](https://user-images.githubusercontent.com/4460564/28233294-76a1cdce-68fe-11e7-94af-d434129ae006.png)
Firefox :
![image](https://user-images.githubusercontent.com/4460564/28233302-825f54c4-68fe-11e7-8ac0-39d965ee5cdb.png)

I think it because chrome doesn't support encoding any more...

Is the text annotation function  will support UTF-8 in the near future ? or there is others options to add the text that will be show good in Chrome ?

Thank you,
Roy

**Comment by Anni619** [comment]
Hi!
I have the same issue( Have you found any solution?

**Comment by nicolaasuni** [comment]
tc-lib-pdf is not TCPDF
