### ISSUE TITLE
Images in the pdf results have some kind of transparency, instead of rendering fully opaque

### ISSUE THREAD

**Issue by arthur-v-abogadil** [tecnickcom/tc-lib-pdf#28]
Hello! Thanks for your work on this package.

I have an issue where the images seem to have some transparency instead of rendering full color,

Please see page 2 of this pdf,
http://customizer.prolook.com/design_sheets/A6D6B362-32E6-5154-93EB-59FC24258811.pdf

Also theres a small thumbnail of a mascot on page 5, the appear to have some king of transparency setting.

The full color of the image which is also the same as the source image being used by the pdf is at
https://s3-us-west-2.amazonaws.com/uniformbuilder/uploads/staging/884ab11e1d16911d3d41aae1334ca4b9.png

Thanks! Any help would be really appreciated.

**Comment by THausherr** [comment]
The SMask images (e.g. the one at `Root/Pages/Kids/[1]/Resources/XObject/I1/SMask`) are weird: I assume you want a clear cutout, i.e. have the "around" part fully transparent and the "inside" part visible. So the SMask image bytes should all (or mostly) be 00 or FF. But they are 00 or AD.

(I'm not with this project, I just like looking at troublesome PDFs).

**Comment by arthur-v-abogadil** [comment]
The around is already fully transparent its the main images that somehow had transparency hence it looking not fully visible.

**Comment by nicolaasuni** [comment]
tc-lib-pdf is not TCPDF
