### ISSUE TITLE
Bower Support

### ISSUE THREAD

**Issue by evanrich** [tecnickcom/tc-lib-pdf#3]
Can Bower support be added so that this can be pulled via Bower?   Bower can do git pulls, but a module would be better.

**Comment by nicolasbui** [comment]
TCPDF already support Composer, the most famous package manager for PHP.... Bower is a packager manager is not for PHP but JavaScript/Html package.

**Comment by nicolaasuni** [comment]
Thanks for the suggestion.
At least until the project is in a usable state I will stick with Composer.
This project will be also available as RPM and DEB package.
