### ISSUE TITLE
PDF signature corrupt when exceeding max length

### ISSUE THREAD

**Issue by vic-cw** [tecnickcom/tc-lib-pdf#31]
This error has occurred on TCPDF 6.0.87. I am not sure whether it will still occur in tc-lib-pdf.

When signing a PDF document, if signature exceeds `signature_max_length`, no error gets caught, no error message gets printed, but PDF document becomes corrupt.

When opening a signed PDF in Adobe Reader, it shows these errors :

While opening the file, it says
> This file is damaged but is being repaired

The blue ribbon on top says
> Certification by is invalid

When opening the signature panel, it says
> Certified by %s

Details of errors say
> There are errors in the formatting or information contained in this signature (support information: SigDict /Contents illegal data)

When clicking on "Certificate details", nothing happens

Screenshot:

![Screenshot of problem](https://i.stack.imgur.com/fk7gV.png)

A sample PDF so signed can be found at https://witnesser.co/images/158571879168934339.pdf

A solution could probably be to detect signature length before inserting it, check whether it fits limit, and if not, either throw an error, or increase limit.

**Comment by nicolaasuni** [comment]
tc-lib-pdf is not TCPDF
