### ISSUE TITLE
Doc 404 page not found errors

### ISSUE THREAD

**Issue by elasticsteve** [tecnickcom/tc-lib-pdf#33]
All the pages in the docs show 404 page not found. Any idea?

Example:
[https://tcpdf.org/docs/srcdoc/tcpdf/class-TCPDF](https://tcpdf.org/docs/srcdoc/tcpdf/class-TCPDF)

**Comment by ZurabWeb** [comment]
Works well:

![image](https://user-images.githubusercontent.com/12236085/35630702-19fe8ff2-0670-11e8-8bd3-388bbdb2d689.png)

**Comment by elasticsteve** [comment]
works now. didn't work yesterday.
