### ISSUE TITLE
@6.2 - mcrypt_get_cipher_name is deprecated

### ISSUE THREAD

**Issue by piernik** [tecnickcom/tc-lib-pdf#38]
I can't  post it on `tcpdf@6.2` github version.
As of `php 7.1` `mcrypt_get_cipher_name` is deprecated. Can You change it?

http://php.net/manual/en/function.mcrypt-get-cipher-name.php

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
