### ISSUE TITLE
What is the status of this library ?

### ISSUE THREAD

**Issue by jmleroux** [tecnickcom/tc-lib-pdf#39]
Thanks for all the amazing work.
I'm a big fan of TCPDF and use it in multiple projects, and I'd love to use an more up to date library.
Is this library useable for simple needs ?
Is there a roadmap or a backlog where we could pick tickets if we want to help ?

**Comment by ZurabWeb** [comment]
@jmleroux It seems like it's abandoned, there have not been any updates to the repo in a few months now. I would use the old version if I were just starting to implement the feature.

**Comment by nicolaasuni** [comment]
This library is still under development.
Most of the code has been already ported to external libraries (see dependencies).
Some core code needs to be completed but I don't find much time these days,

**Comment by VeeK727** [comment]
Any updates on the library? When do you think will it complete?
