### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by standus** [tecnickcom/tc-lib-pdf#4]
Please prepare library for PHP 7.1 and deprecated mcrypt_*
see https://wiki.php.net/rfc/mcrypt-viking-funeral

**Comment by nicolaasuni** [comment]
Thank you for pointing out this.
All the cryptographic methods have been already moved to tc-lib-pdf-encrypt and they currently use mcrypt only if it is installed and openssl is not available.

**Comment by standus** [comment]
When it will be ready for production?

------ Původní zpráva ------
Od: "Nicola Asuni" <notifications@github.com>
Komu: "tecnickcom/tc-lib-pdf" <tc-lib-pdf@noreply.github.com>
Kopie: "standus" <standus@post.cz>; "Author" <author@noreply.github.com>
Odesláno: 5. 10. 2016 23:04:59
Předmět: Re: [tecnickcom/tc-lib-pdf] PHP 7.1 (#4)
