### ISSUE TITLE
Emoji in text

### ISSUE THREAD

**Issue by tbrand-aa** [tecnickcom/tc-lib-pdf#40]
I'm generating PDF files on the fly with user content which could contain emoji-characters.
Currently I'm using a custom font and emoji-characters don't get displayed in the PDF (some are totally hidden, some are printed in unknown characters).

To be honest, I don't know exactly where to start looking. Should my custom font include the emoji-characters? Or can I do something else to include them?
I've tried both `MultiCell` and `writeHTMLCell`.

Thanks!

**Comment by rkgarcia** [comment]
Are you setting the emoji custom font?

**Comment by tbrand-aa** [comment]
I'm using a 'handwritten'-style font for my text in the PDF. I think it does not contain any emoji (not sure if this is required).

> Are you setting the emoji custom font?
What do you mean with this? Do I need to split the text and define a different font, or something else?

Font I use: https://www.dafont.com/blokletters.font

**Comment by EvilJordan** [comment]
Did you figure this out? Do emojis need to 1) be identified and 2) assigned a special font in order to appear in PDF text?

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
