### ISSUE TITLE
About TCPDF flags.

### ISSUE THREAD

**Issue by KrYpToDeN** [tecnickcom/tc-lib-pdf#41]
Hello.

There is a code in TCPDF

`$pdf->Button('submit', 30, 10, 'Submit', array('S'=>'SubmitForm', 'F'=>'http://localhost.ru/pdf.php#XFDF', 'Flags'=>array('ExportFormat')), array('lineWidth'=>2, 'borderStyle'=>'beveled', 'fillColor'=>array(128, 196, 255), 'strokeColor'=>array(64, 64, 64)));`

Could you, please, tell me, where can i see all array Flags (such as 'F', 'S', 'ExportFormat' and so on).
I can't find it in documentation.

Thank you!

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
