### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by ghost** [tecnickcom/tc-lib-pdf#42]
Hi Guy!

Really thank you for make PDF library.  It is very useful.

I have problem when make pdf with add `timestamp` and `signature` for pdf. Do you know any document relative with timestamp and signature function in PDF.  [Example]( https://www.setasign.com/products/setapdf-signer/demos/digital-signature-with-a-time-stamp/#p-596)

Hope you reply to me. 
Thanks so much

**Comment by MxRay** [comment]
I'm in need of the exact same thing. This feature would be really appreciated!

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
