### ISSUE TITLE
How to create PDF from HTML?

### ISSUE THREAD

**Issue by nnrudakov** [tecnickcom/tc-lib-pdf#43]
Examples from docs doesn't works.
```php
Call to undefined method Com\Tecnick\Pdf\Tcpdf::writeHTML()
```

**Comment by waltercruz** [comment]
it seems that HTML is not yet supported on this new version...

**Comment by ppKrauss** [comment]
See also https://print-css.rocks/

**Comment by nicolaasuni** [comment]
The HTML support will come after everything else will be implemented.
I hope to find some more time next year to complete this.
