### ISSUE TITLE
PDF/A 1b Validation

### ISSUE THREAD

**Issue by oudoken** [tecnickcom/tc-lib-pdf#44]
Hi there,
Thanks for TCPDF.

I've encountered some problems with validating PDF/A 1b seems there's a missing definition for:
`<pdfaSchema:schema>Adobe PDF Schema</pdfaSchema:schema>`

Apache preflight validation (java -jar preflight-app-2.0.11.jar flie-xxx.pdf) lead to:
`7.5 : Error on MetaData, Missing pdfaSchema:property in type definition`

Btw adding an extra definition to pdf schema solve the problem i've added a pull request for reference.

Also VeraPDF validation fails for font-glyphs related problem but seems that VeraPDF has some problems in fonts handling.

Thanks kind regards
Rob

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
