### ISSUE TITLE
Tcpdf::setDisplayMode()

### ISSUE THREAD

**Issue by dafap** [tecnickcom/tc-lib-pdf#47]
PHP7.2.9
Accessing static property Com\Tecnick\Pdf\Tcpdf::$valid_zoom as non static in D:\www\photon\SchoolBusManager\vendor\tecnickcom\tc-lib-pdf\src\Tcpdf.php on line 170
Cause a warning of `in_array()` function in the same line.
Correct by :

    if (is_numeric($zoom) || in_array($zoom, self::$valid_zoom)) {

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
