### ISSUE TITLE
Accept PRs on the old library to support PHP 7.3?

### ISSUE THREAD

**Issue by briandotdev** [tecnickcom/tc-lib-pdf#48]
I see that TCPDF is now considered obsolete but seeing as this library is still in development I'm wondering if you would accept PRs on the old library that update for PHP 7.3 compatibility?

**Comment by ZurabWeb** [comment]
There's quite a few people interested in this library, but the development is frozen. Old lib is now deprecated and the new lib isn't yet production ready. @nicolaasuni Can you add more contributors so the library continues to develop if you no longer have time to oversee it? It's a shame seeing a good thing get abandoned like that.

**Comment by mcarpenterjr** [comment]
Is there still interest here? I'd like to see this go forward this is the most complete PDf library out there, I have personal motivation to complete this library with signature timestamping. I would be willing to spearhead forking and further developing the library if there is enough interest.
Priorities would be Modern compatability and documentation.

**Comment by nicolaasuni** [comment]
There are some @TODO comments in the current development branch of tc-lib-pdf you can have a look at.
I'd rather use my little time to finish the new library than fix the old one.
