### ISSUE TITLE
tcpdf datauri in writehtml

### ISSUE THREAD

**Issue by AskinSavascisi** [tecnickcom/tc-lib-pdf#49]
Hi, does tcpdf support datauri in writehtml src tags?

(i'm using elibyy/tcpdf-laravel)

i don't want to store the signatures from my clients on my server so instead i've tried to store them as datauri's in my db.

example code:

```
$html .='<img src="'.$data_uri.'" width="300">';
PDF::Writehtml($html);
```

i get an empty space where the signature should come.

i can achieve this with PDF::Image('a'.$datauri) however its not responsive to my pdf then..

Thanks in advance

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues

**Comment by Nyavowoyi** [comment]
I was having the same issue and this is basically how I solved it.

I had a base64 string like: **data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAABkCAYAAACvgC0OAAAaEklEQVR4Xu1dbYxc..........more base 64...**

I used the following code which I got from this answer on StackOverflow **https://stackoverflow.com/a/54520065/7880201**:

$img= '<img src="@' . preg_replace('#^data:image/[^;]+;base64,#', '', $the_base64_str) . '" width="50px">';

In my case, I just stored it an a variable and later output it with the same writeHtml command.
