### ISSUE TITLE
Support "text-decoration" in SVG text

### ISSUE THREAD

**Issue by temuri416** [tecnickcom/tc-lib-pdf#5]
Hi Nicola,

First of all - thank you for tcPDF. You're a life-saver.

Would it be possible to add support for `text-decoration` attribute in SVG text.

Possible styles:
- underline
- overline
- line-through

Currently, `text-decoration` is ignored when SVG is added to PDF.

``` xml
    <g id="28493" transform="translate(201 242)">
        <text font-family="arial" font-size="177" font-weight="normal" text-decoration="underline" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: bevil; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" >
            <tspan x="-59" y="55.75" fill="rgb(0, 0, 0)">A</tspan>
        </text>
    </g>
```

Thanks!

**Comment by temuri416** [comment]
After playing with it some more I found that moving `text-decoration` to `<tspan` works.

```xml
	<g id="28493" transform="translate(201 242)">
		<text font-family="arial" font-size="177" font-weight="normal" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: bevil; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" >
			<tspan x="-59" y="55.75" fill="rgb(0, 0, 0)" text-decoration="underline">A</tspan>
		</text>
	</g>
```

But then, it is rendered as this:

![image](https://cloud.githubusercontent.com/assets/3987203/19572191/41dece0e-96cf-11e6-9093-0d8e234ace37.png)

What do you think?

**Comment by nicolaasuni** [comment]
The new SVG support will be added once the basic functionalities will be reimplemented.
