### ISSUE TITLE
Anyone have success with signatures and timestamping? 

### ISSUE THREAD

**Issue by mcarpenterjr** [tecnickcom/tc-lib-pdf#51]
TCPDF is currently my backbone when it comes to creating PDFs on the fly, everything else just seems to fall short when you get into complex requirements like emailing printing and now signing. Seriously thanks for all that!

We're running into an issue with the previous library and time stamping, I can see it was planned but never implemented, and I'm beginning to see why; it's not really complex just more of a pain to get the tsq for the pdf.

Essentially this is the process as I understand it, (I'm totally open for correction as I am nearly fried at this point with all of this)

1. get a signing request -
  * to do this we need to do something like `openssl ts -query -data TCPDFFILE.pdf -no_nonce -sha512 -cert -out file.tsq`
  * Does anyone know the options for sending the PDF? does it have to be a file? could it be a string? Is there a way to write to a file object without tripping the output error inside TCPDF "Some output has already been written..."?
2. CURL the tsq to the time stamp authority, which is pretty straightforward. We should get the tsr back.
3. read the tsr that was sent back and then insert it into the PDF Signature.

If it were possible, I would think it would make sense to just emit the response from the timestamp authority to a variable to later be inserted into the signature. Same thing with the cert?

Like I said though, this is all very new to me and I'm looking to better understand the process to better implement it.

**Comment by nicolaasuni** [comment]
The signing will be reimplemented at some point in this new library.
