### ISSUE TITLE
I like to help with this library

### ISSUE THREAD

**Issue by mklemarczyk** [tecnickcom/tc-lib-pdf#53]
Hi there,

Can you define interface that library will be defined?
Thanks to interface, we can fill it with implementation and go on with development of this great library.

Do you have plan for creating PDF content?

Best regards,
Maciek

**Comment by nicolaasuni** [comment]
If you look at the Output.php file there are emtpy functions marked with "@TODO".
The logic of these should be imported from the old TCPDF library.

**Comment by ZurabWeb** [comment]
@nicolaasuni man you've been away for way too long, do you want to maybe appoint a few people with privileges to merge code so that the project doesn't just die out? We've been willing and unable to contribute for quite some time now.

**Comment by thomasphansen** [comment]
I'd also like to contribute for this project! :) Will check the TODO's and see what I can help with! :)

**Comment by Baruch4413** [comment]
Maybe someone should just clone the repo and create a new project, hopefully with @nicolaasuni 's blessing

**Comment by CreativeNative** [comment]
@nicolaasuni Any updates here? I'm also really very interested in this project.

**Comment by k00ni** [comment]
Hello, can anyone give me some information about:
1. How "complete" is this library? 
2. Is it worth investing energy in forking it or should one stay with its predecessor (https://github.com/tecnickcom/TCPDF)?

No offence to the authors, but the current situation is not bearable for projects or people relying on this code.

Test coverage is at 11%, but its predecessor has no tests at all. At least here we would have a basement for improvements. But i think it comes down to the question, if its complete. If not, maybe staying with the battle proofed predecessor is the safer option.

I can create a fork of this library and move it to an organization. That would allow more options and flexibility for community management. But before that, i would like to know up front, who can help maintaining it in the future? My knowledge in the PDF extraction and generation is **very limited**, but i have experience in running/helping Open Source projects.

**Comment by nicolaasuni** [comment]
Any contribution is welcome but please do not confuse TCPDF with this new tc-lib-pdf rewrite.
Please get in touch if there is an area you would to take in.
