### ISSUE TITLE
&nbsp; at the end inside element error

### ISSUE THREAD

**Issue by itajackass** [tecnickcom/tc-lib-pdf#55]
I get a strange problem Using writeHTML with a string like this:

`$string = '<p>TEST&nbsp;</p>';`

I get empty when i use writeHTML. After some test i see that appened if `&nbsp;` is at the end, inside an element like `<p>`, `<span>`, etc... only at the end.

I get this error on old version of TCPDF, i don't know if it appened also in this new version

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
