### ISSUE TITLE
TCPDF 6.2.22 and later breaks multi usage of the same image

### ISSUE THREAD

**Issue by chilek** [tecnickcom/tc-lib-pdf#56]
As in subject. All versions prior to 6.2.21 are not affected.
From 6.2.22 when you use the same image many times in your pdf only first appearance is supported properly. All following links to the same image are not visible/broken.
In my opinion code from TCPDF::_destroy() should not always delete images stored in cache located at K_PATH_CACHE setting. If you need more info please let me know.

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
