### ISSUE TITLE
Width and X position of scaled MultiCells

### ISSUE THREAD

**Issue by Harmageddon** [tecnickcom/tc-lib-pdf#57]
I noticed an odd behavior of `MultiCell`s in transformations (especially scaling). It doesn't occur in `Cell`s, but I suppose it might occur as well in other elements that are modified to fit the page dimensions.
Within a down-scaled part of the document, positions such as (230, 50) are still visible on a standard A4 page, because the dimensions get scaled down according to the transformation. However, TCPDF seems to force elements into the 210mm width of an A4 page, without scaling this page dimension or the margins. I modified example_013 from the documentation to illustrate my case, the code can be seen [here](https://gist.github.com/Harmageddon/3d95cc38ce4173d9be2119d7e20b156e). The resulting PDF is [example_013.pdf](https://github.com/tecnickcom/tc-lib-pdf/files/3191500/example_013.pdf).

Tested with TCPDF 6.2.11, 6.2.26 and `master` from https://github.com/tecnickcom/TCPDF.

Has anyone else encountered a similar behaviour with TCPDF and has an idea how to solve this? I have debugged this for some time now and suspect that it has something to do with the position and width calculations inside `MultiCell`, but I'm not sure how exactly this can be fixed.

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
