### ISSUE TITLE
Font Awesome importing

### ISSUE THREAD

**Issue by stormriderstudios** [tecnickcom/tc-lib-pdf#58]
I've just started working with the previous/current/other version of tcpdf and tried to import the "font awesome" fonts.

I managed to convert the OTF font files to TTF
I used the tool to convert the TTF to the 3 files in the font folder
Using the SetFont function I loaded the "fontawesome" font
I added text using Write and writeHTML 

However, when I generate the pdf file I get other special characters and blocks.

I'm wondering the following:
- Am I doing something wrong and should it work?
- If not will the new version fix it?
- Could Font Awesome be bundled into the new version?

Thanks!

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
