### ISSUE TITLE
Stop setting mbstring.internal_encoding

### ISSUE THREAD

**Issue by animike** [tecnickcom/tc-lib-pdf#60]
The option was deprecated in PHP 5.6. It generates a sort of incompatibility when different libraries are using the mbstring module, for example, another library could not use mbstring safely for as long a TCPDF instance is being used.

References:
https://www.php.net/manual/es/mbstring.configuration.php#ini.mbstring.internal-encoding
https://sourceforge.net/p/tcpdf/bugs/1106/
https://github.com/spipu/html2pdf/issues/435

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
