### ISSUE TITLE
Automatic adjustment of cell width

### ISSUE THREAD

**Issue by sscbc** [tecnickcom/tc-lib-pdf#62]
Hi there,
Let say i have a document just for an example with a width of 100
I create 6 cells
1st cell = 10 width
2nd cell = ?
3rd cell = 20 width
4th cell = 20 width
5th cell = 20 width
6th cell = 20 width
I just want to ask if is it possible that the 2nd cell can adjust its width given the width of other cells just to fit the whole width of a document?
for example the above widths will have a total of 90 so the 2nd cell should automatically adjust to 10 since the total width of document is 100
Is it possible?

**Comment by LittleBigFox** [comment]
Hi!

No it's only possible with %...

Regards,
LBF

**Comment by sscbc** [comment]
Thank you for the response
What do you mean sir by %?
I have to use % when setting the cell width?

**Comment by LittleBigFox** [comment]
Hi!
Yes, style in percent. For exemple:

```
<tr>
<td style="width:10%;"></td>
<td style="width:10%;"></td>
<td style="width:20%;"></td>
<td style="width:20%;"></td>
<td style="width:20%;"></td>
<td style="width:20%;"></td>
</tr>
```

**Comment by sscbc** [comment]
What about sir for dynamic columns?

**Comment by LittleBigFox** [comment]
Oh sorry, i'm not in the good project, all my excuses :o 

I talked about a project based on tc-lib-pdf... So sorry!

Regards,
LBF

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
