### ISSUE TITLE
RTL text justification

### ISSUE THREAD

**Issue by matrixall** [tecnickcom/tc-lib-pdf#63]
I would like to report tow issues with **MultiCell** when justifying RTL text specifically Arabic:
_1-when justify arabic text, the text get justifying to left only unless I force horizontal scaling to 2_ 
_2- at the last line when add **\n**, it gets justified to the left instead of the right
[https://ibb.co/bHHWpMS](url)

**Comment by nicolaasuni** [comment]
Please report this to:
https://github.com/tecnickcom/TCPDF/issues
