### ISSUE TITLE
PDF/X-4 support planned?

### ISSUE THREAD

**Issue by lazi3b0y** [tecnickcom/tc-lib-pdf#64]
Like the title states, are you planning on adding support for PDF/X-4 in the near future? :)

**Comment by nicolaasuni** [comment]
Thank you for your suggestion.

tc-lib-pdf now supports PDF/X and PDF/UA conformance modes.

For more details, please see this pull request:
https://github.com/tecnickcom/tc-lib-pdf/pull/158
