### ISSUE TITLE
Feature Request: to support MathML <math> tags

### ISSUE THREAD

**Issue by squido75** [tecnickcom/tc-lib-pdf#66]
It is becoming common to insert mathematical equations and symbols in HTML, using the `<math xmlns="http://www.w3.org/1998/Math/MathML">` tags.  Many editors are supporting MathML, e.g. CKEditor.

Currently, TCPDF/tc-lib-pdf does not break when encoutering `<math>`, however, the output is erratic.  Sometimes it outputs as "?", sometimes it outputs as a string of numbers ignoring the mathematical notations.

It would be good if `<math>` can be supported. Thank you.

P.S.: I do not know which project to raise this feature request in, so I'm raising it in both TCPDF and tc-lib-pdf projects.

**Comment by nicolaasuni** [comment]
Hi, I will take this into consideration for when the port of the existing features is completed.
