### ISSUE TITLE
Raise PHP requirements

### ISSUE THREAD

**Issue by Hackwar** [tecnickcom/tc-lib-pdf#67]
Please consider raising the minimum requirements for your project to for example PHP 7.2. You are creating a new library and there is no reason to support PHP versions, which haven't been supported for a year or in case of 5.6, several years. Whoever is using your library also is starting over and I don't see anyone running your code on something lower than PHP 7.2, maybe even just PHP 7.4, especially considering that you don't have a date for a release yourself yet.

**Comment by nawlbergs** [comment]
Those are some pretty big assumptions your making there.

**Comment by Hackwar** [comment]
From what I could see so far, this rewrite is not a drop-in replacement of the original tcpdf. Switching over from the monolithic class to this set of libs will mean considerable rework of the code. I couldn't come up with a scenario where someone would invest all the work to switch over to this new library and NOT update the PHP version to something remotely current in the process. Considering the difficulties to support all these versions with your code, I just want to make your life easier by this. Even including support for PHP 7.2 should be considered conservative, since it is going to be EOL at the end of this month.

To a maintainer of a FOSS project from another maintainer of a rather large FOSS project and one that has been responsible at a time for a large part of the installed base of TCPDF. ;-)

**Comment by nicolaasuni** [comment]
@Hackwar thank you for your suggestion.
There is currently a large base of users with very old PHP version.
So far the backward compatibility has worked well, I will consider deprecating old PHP versions when I will need to add a new feature that is not supported in older versions.
