### ISSUE TITLE
Consider dropping support for php 5.4

### ISSUE THREAD

**Issue by tcitworld** [tecnickcom/tc-lib-pdf#7]
php 5.4 is dead for over a year now, maybe support for it could be dropped. It should avoid compatibility issues like https://github.com/tecnickcom/tc-lib-pdf/commit/60a068e4f188ab3b248506fa8cd4e1c916574458
Version 5.5 is also dropped since a few months (just saying :smile:  )
See https://secure.php.net/supported-versions.php

**Comment by nicolaasuni** [comment]
Thanks for your suggestion.
