### ISSUE TITLE
Support for multiple digital signature

### ISSUE THREAD

**Issue by galihlasahido** [tecnickcom/tc-lib-pdf#74]
Hi There,

Please add a features so that this can support multiple digital signature in one file pdf

**Comment by mahouha** [comment]
is now available ?

**Comment by galihlasahido** [comment]
do you have any article on what needs to add on to do this? maybe if there's an article or guide i can try to contribute

**Comment by nicolaasuni** [comment]
The current version now includes the signature features as in TCPDF.
For extensions I will accept PRs that follows the same guidelines and are test-covered.
