### ISSUE TITLE
Installation/usage issues with tc-lib-pdf

### ISSUE THREAD

**Issue by th3penguinwhisperer** [tecnickcom/tc-lib-pdf#8]
Hi,

First of all: thank you for your continuous efforts on TCPDF/tc-lib-pdf.
I've been looking into what library I should be using and yours seems to be having quite some features.

I've tried using tc-lib-pdf however I didn't got it to work and I'm unsure what I'm doing wrong.
When trying TCPDF I had no issues and could rather quickly find my way into creating a basic PDF. However I wonder what's the use of learning the "old" TCPDF when you're building tc-lib-pdf as it's successor(I'd rather immediately go that way). I've been trying to find some basic example on how to use your code but that fails.

IMHO I think the examples are great for TCPDF but the site is misleading in refering to the tc-lib-pdf repo by default (I only noticed after a while that that is why the examples didn't work).
Also: the installation notes seem very limited(actually hit the API limiter on github with the instructions on the site). I understand you want to make use of some technologies like composer. However for someone who's not been working with PHP that much recently it's unclear on what steps are now needed to make actual use of your project(for example the site refers to creating a composer.json but not if you'd need to execute anything else like: composer install).

My actual question is if you'd be so kind to make a basic project example using tc-lib-pdf.
So for example:
Get the git repository:
git clone ...
Get the dependencies;
composer install
Create a file:
example.php
Add the following to example.php to include tc-lib-pdf to your project (to make use of the namespaces, ...):
...
You can create a basic PDF like this:
...
To create and view the docs do;
...

And maybe clearly differentiate on the website between TCPDF and tc-lib-pdf (with the different repo names).

I think it'd help a lot of people in getting on the new tc-lib-pdf wagon.

Thanks in advance for your continuous efforts!

**Comment by princeofnaxos** [comment]
+1

**Comment by exactquery** [comment]
I could be wrong, but from what I can tell this library is not yet ready to be a replacement for TCPDF.  It has only recently been published, and is still listed as 'Under Development'.  Most of what you are asking about is likely to come with time.

**Comment by princeofnaxos** [comment]
So what is the timeframe? And how will the upgrade path look? I'm starting a whole new PDF project and wish to avoid a lot of extra work when moving to the new library. 

Edwin Boersma
Fasterminds
http://www.fasterminds.com

Tel.: +46709726431
Tel.: +46313011801

**Comment by nicolaasuni** [comment]
Unfortunately there is no timeframe as I am working on this on my spare time.

**Comment by temuri416** [comment]
@nicolaasuni 

We all know you're busy and appreciate the work you're doing. Could you please tell us if there's any progress made on the new library? There aren't any new commits to this repo - so we're just wondering.

Best wishes & thanks.
