### ISSUE TITLE
the project is not usable : Missing at least 2 properties

### ISSUE THREAD

**Issue by jonathangreco** [tecnickcom/tc-lib-pdf#82]
Hi I started to use your library today and I've encounter 3 issues : 

I'm using this to configure : 

```
        foreach ($documents as $invoiceNumber => $document) {

            $pdf = new Tcpdf();
            $pdf->setCreator('client');
            $pdf->setAuthor('compta@client.com');
            $pdf->setTitle($invoiceNumber);
            $pdf->setSubject('invoice');
            $pdf->setKeywords("facture, {$invoiceNumber}");
            $pdf->page->add();
            $pdf->page->addContent($document);

            file_put_contents("../var/invoices/{$invoiceNumber}.pdf", $pdf->getOutPDFString());
        }
```

first error I encountered: 

`
Warning: Undefined property: Com\Tecnick\Pdf\Tcpdf::$outlines
`

And yes of course the property is defined nowhere so I added it on MetaInfo.php#130 : 

`protected $outlines = [];`

Then the second error kicked in : 

` Warning: Undefined property: Com\Tecnick\Pdf\Tcpdf::$signature`

so I tried to add in Output#58 : 
it's weird that this array is not defined anywhere by the way

```
    protected $signature = [
        'appearance' => [
            'empty' => []
        ]
    ];
```

But then I got : 

`Warning: Undefined variable $out` (in getOutSignatureFields)

And of course the method here is completely messed up. $out not defined out of the foreach for a property that is not existing.

I tried (without knowing if I was doing any good) to modify `getOutSignatureFields`  in Output.php#876

```
    protected function getOutSignatureFields()
    {
        $out = '';
        foreach ($this->signature['appearance']['empty'] as $key => $esa) {
            $page = $this->page->getPage($esa['page']);
            $signame = $esa['name'].sprintf(' [%03d]', ($key + 1));
            $out .= $esa['objid'].' 0 obj'."\n"
                .'<<'
                .' /Type /Annot'
                .' /Subtype /Widget'
                .' /Rect ['.$esa['rect'].']'
                .' /P '.$page['n'].' 0 R' // link to signature appearance page
                .' /F 4'
                .' /FT /Sig'
                .' /T '.$this->getOutTextString($signame, $esa['objid'])
                .' /Ff 0'
                .' >>'
                ."\n".'endobj';
        }
        return $out;
    }
```

Now, I've got no error, but PDF is empty.

Can you assist ?

**Comment by nicolaasuni** [comment]
This library is not complete but it can already generate PDF documents.
Please check the example at examples/index.php
