### ISSUE TITLE
How do I add text to a document?

### ISSUE THREAD

**Issue by nilcay** [tecnickcom/tc-lib-pdf#86]
Text is the most basic function, but no example can be found.

**Comment by Nyavowoyi** [comment]
> Text is the most basic function, but no example can be found.


Have a look at this 
https://tcpdf.org/examples/example_001/

**Comment by nicolaasuni** [comment]
There is now an example at examples/index.php.
Unfortunately as now the text support is very basic.
More to come as I find more time...
