### ISSUE TITLE
Radio Button as Initial State True Does Not Appear in Rendered PDF

### ISSUE THREAD

**Issue by richnwilson** [tecnickcom/tc-lib-pdf#9]
I am using PHP code to set the initial state on a radio button.  When I view the rendered PDF it doesn't show the checked button. I can mouse over and check the 'hidden' button and it then shows as checked --- any ideas ?

Using TCPDF 6.2.13 with Adobe Reader 15.020.20039 on Windows 7

**Comment by richnwilson** [comment]
UPDATE: Let me revisit my code. I have run the Example014 and that does work correctly. I assume it's human error.

**Comment by nicolaasuni** [comment]
This is a new library, the support for TCPDF is ended and the project will be deprecated once this new one will be completed.
