### ISSUE TITLE
 This PDF document probably uses a compression technique

### ISSUE THREAD

**Issue by MilesHart** [tecnickcom/tc-lib-pdf#91]
When I merge two documents where one has a new PDF compression method

**To Reproduce**
Merge two PDF, usually generated by latest version of MS office with the Adobe PDF printer. Assign to merge

**Expected behavior**
For them to merge

**Logs**
This PDF document probably uses a compression technique which is not supported by the free parser shipped with FPDI

**Environment:**
 - OS: Windows
 - PHP version: 7.3.1
 - Version:

Full error:

setasign\Fpdi\PdfParser\CrossReference\CrossReferenceException: This PDF document probably uses a compression technique which is not supported by the free parser shipped with FPDI. (See https://www.setasign.com/fpdi-pdf-parser for more details) in file C:\{...}\vendor\setasign\fpdi\src\PdfParser\CrossReference\CrossReference.php on line 257

#0 C:\{...}\vendor\setasign\fpdi\src\PdfParser\CrossReference\CrossReference.php(209): setasign\Fpdi\PdfParser\CrossReference\CrossReference-&gt;initReaderInstance(Object(setasign\Fpdi\PdfParser\Type\PdfIndirectObject))
#1 C:\{...}\vendor\setasign\fpdi\src\PdfParser\CrossReference\CrossReference.php(67): setasign\Fpdi\PdfParser\CrossReference\CrossReference-&gt;readXref(232320)
#2 C:\{...}\vendor\setasign\fpdi\src\PdfParser\PdfParser.php(157): setasign\Fpdi\PdfParser\CrossReference\CrossReference-&gt;__construct(Object(setasign\Fpdi\PdfParser\PdfParser), 0)
#3 C:\{...}\vendor\setasign\fpdi\src\PdfParser\PdfParser.php(205): setasign\Fpdi\PdfParser\PdfParser-&gt;getCrossReference()
#4 C:\{...}\vendor\setasign\fpdi\src\PdfParser\PdfParser.php(181): setasign\Fpdi\PdfParser\PdfParser-&gt;getCatalog()
#5 C:\{...}\vendor\setasign\fpdi\src\PdfReader\PdfReader.php(84): setasign\Fpdi\PdfParser\PdfParser-&gt;getPdfVersion()
#6 C:\{...}\vendor\setasign\fpdi\src\FpdiTrait.php(217): setasign\Fpdi\PdfReader\PdfReader-&gt;getPdfVersion()
#7 C:\{...}\vendor\webklex\laravel-pdfmerger\src\PDFMerger\PDFMerger.php(224): setasign\Fpdi\Fpdi-&gt;setSourceFile(Object(setasign\Fpdi\PdfParser\StreamReader))
#8 C:\{...}\vendor\laravel\framework\src\Illuminate\Collections\Traits\EnumeratesValues.php(245): Webklex\PDFMerger\PDFMerger-&gt;Webklex\PDFMerger\{closure}(Array, 0)
#9 C:\{...}\vendor\webklex\laravel-pdfmerger\src\PDFMerger\PDFMerger.php(252): Illuminate\Support\Collection-&gt;each(Object(Closure))
#10 C:\{...}\vendor\webklex\laravel-pdfmerger\src\PDFMerger\PDFMerger.php(199): Webklex\PDFMerger\PDFMerger-&gt;doMerge(NULL, false)
#11 C:\{...}\app\Http\Controllers\PdfController.php(59): Webklex\PDFMerger\PDFMerger-&gt;merge()
#12 C:\{...}\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\PdfController-&gt;merge2(Object(Illuminate\Http\Request))

**Comment by TheArKaID** [comment]
This is not the problem of tc-lib-pdf, but FPDI.

Wondering if there's an alternative for FPDI that will support PDF above 1.4, without making it commercial.

*Just throwing another issue, not solution.
